# Ztpfw gitops
clusterGroup:
  name: ztp 
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
    - multicloud-ztpfw-ztp
    - open-cluster-management
    - openshift-pipelines

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5
      csv: advanced-cluster-management.v2.5.0

  projects:
  - hub

  applications:
 
