clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: false

  namespaces:
  - open-cluster-management
  - openshift-pipelines

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5
      csv: advanced-cluster-management.v2.5.0

  projects:
  - hub
  - config-demo

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA


            #   imperative:
            #     # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
            #     # The default schedule is every 10 minutes: imperative.schedule
            #     # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
            #     # imagePullPolicy is set to always: imperative.imagePullPolicy
            #     # For additional overrides that apply to the jobs, please refer to
            #     # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
            #     jobs:

            #   managedClusterGroups:
            #     region-one:
            #       name: region-one
            #       helmOverrides:
            #       - name: clusterGroup.isHubCluster
            #         value: false
            #       clusterSelector:
            #         matchLabels:
            #           clusterGroup: region-one

