# Ztpfw gitops
clusterGroup:
  name: ztp 
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
    - multicloud-ztpfw-ztp
    - open-cluster-management
    - openshift-pipelines

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5
      csv: advanced-cluster-management.v2.5.0

  projects:
  - hub


# argocd project for grouping
  projects:
  - cluster
  - hub

# commented out are optional with default values
  applications:
    nfs:
      name: nfs
      project: cluster
      path: charts/ztphub/nfs
      server: "192.168.150.1"
      # maxpv: 10
      # pv_size: "200Gi"
      # access_modes:  "ReadWriteOnce"
      # claim_policy: "Recycle"
      #
      #    http:
      #      name: httpd
      #      project: hub
      #      path: charts/ztphub/http
      #      domain: lab.local
      # cpu_limit: "200m"
      # memory_limit: "200Mi"
      # access_modes: "ReadWriteOnce"
      # pvc_size: "200Gi"

