{{ $http_values := .Values.clusterGroup.applications.http }}
#{{ $domain :=  `{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec.domain }}` }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $http_values.name }}
  labels:
    app: {{ $http_values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $http_values.name }}
  template:
    metadata:
      labels:
        app: {{ $http_values.name }}
    spec:
      volumes:
        - name: {{ $http_values.name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ $http_values.name }}-pv-claim
      containers:
        - name: {{ $http_values.name }}
          resources:
            limits:
              cpu: {{ $http_values.cpu_limit | default "200m" | quote }}
              memory: {{ $http_values.memory | default "200Mi"| quote }}
          image: registry.access.redhat.com/rhscl/httpd-24-rhel7:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/www/html"
            name: {{ $http_values.name }}-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $http_values.name }}-server-service
spec:
  type: ClusterIP
{{- if eq $http_values.clusterIP "None" }}
  clusterIP: None
{{- end }}
  selector:
    app: {{ $http_values.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $http_values.name }}-pv-claim
spec:
  accessModes:
    - {{ $http_values.accessModes| default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $http_values.pvc_size | default "200Gi" | quote }}
      
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $http_values.name }}
  name: {{ $http_values.name }}-server-route
  namespace: default
spec:
  host: http-server.{{ .Values.global.hubClusterDomain }}
  subdomain: http-server
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ $http_values.name }}-server-service
